###### The motion controlling interface

### Action Service Goal

# The point to reach
Point target

# The plan as a path
nav_msgs/Path plan

---

### Action Server Result

# The reached point when the plan has been followed.
Point reached_point

---

### Action Server Feedback
