###### The motion planning interface

### Action Server Goal

# The point to reach
Point target

---

### Action Server Result

# The plan, i.e., the `via_points` to reach the `target` given the current position.
nav_msgs/Path plan

---

### Action Server Feedback
